FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/vite.config.ts /etc/nginx/conf.d/default.conf.template
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
