import { Scheme, EvaluationOutcome, BenchmarkMetrics } from '../types';

export const MOCK_SCHEMES: Scheme[] = [
  {
    id: 'post-matric-sc-scholarship',
    title: 'Post-Matric Scholarship for Scheduled Caste Students',
    category: 'Education',
    state: 'Central / All States',
    language: 'English',
    version: 'v2.1',
    last_amended: '2026-04-15',
    summary: 'Financial assistance for SC students pursuing post-secondary education with annual family income up to ₹2,50,000.',
    conditions: [
      {
        id: 'c1',
        field: 'caste_category',
        field_display: 'Caste Category',
        operator: 'eq',
        value: 'SC',
        original_clause: 'Applicant must belong to Scheduled Caste (SC) category.',
        mutability: 'IMMUTABLE',
        confidence: 0.98,
        language: 'en',
        is_current: true,
        valid_from: '2024-01-01',
      },
      {
        id: 'c2',
        field: 'education_level',
        field_display: 'Minimum Qualification',
        operator: 'gte',
        value: '10th',
        unit: 'grade',
        original_clause: 'Must have passed 10th grade matriculation exam.',
        mutability: 'MUTABLE',
        confidence: 0.95,
        language: 'en',
        is_current: true,
        valid_from: '2024-01-01',
      },
      {
        id: 'c3',
        field: 'income_threshold',
        field_display: 'Family Annual Income Limit',
        operator: 'lte',
        value: 250000,
        unit: 'INR',
        original_clause: 'Total annual family income must not exceed Rs. 2,50,000.',
        mutability: 'MUTABLE',
        confidence: 0.96,
        language: 'en',
        is_current: true,
        valid_from: '2024-01-01',
      },
    ],
    documents: [
      { id: 'd1', title: 'Caste Certificate (SC)', required_for_fields: ['caste_category'], issuing_authority: 'Tehsildar / District Revenue Officer' },
      { id: 'd2', title: 'Annual Income Certificate', required_for_fields: ['income_threshold'], issuing_authority: 'Revenue Department' },
      { id: 'd3', title: '10th Marksheet / Passing Certificate', required_for_fields: ['education_level'], issuing_authority: 'State Secondary Education Board' },
    ],
    benefits: [
      { id: 'b1', title: 'Full Tuition Fee Reimbursement', description: 'Complete coverage of college maintenance & mandatory non-refundable fees.' },
      { id: 'b2', title: 'Monthly Maintenance Allowance', amount: '₹1,200', frequency: 'Monthly', description: 'Hostel and living expense allowance for hostellers and day scholars.' },
    ],
    exclusions: [
      { id: 'e1', title: 'Income Tax Payer Exclusion', condition_field: 'income_tax_payer_status', condition_value: 'true', original_clause: 'Students whose parents paid income tax in the last assessment year are excluded.', overrides_all: true },
    ],
  },
  {
    id: 'pm-kisan-samman-nidhi',
    title: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    category: 'Agriculture',
    state: 'Central',
    language: 'English',
    version: 'v3.0',
    last_amended: '2026-02-10',
    summary: 'Direct income support of ₹6,000 per year in three equal installments to small & marginal farmer families.',
    conditions: [
      {
        id: 'pm1',
        field: 'land_ownership_ha',
        field_display: 'Cultivable Land Area',
        operator: 'lte',
        value: 2.0,
        unit: 'hectares',
        original_clause: 'Farmer family owning cultivable landholding up to 2 hectares.',
        mutability: 'MUTABLE',
        confidence: 0.97,
        language: 'en',
        is_current: true,
        valid_from: '2024-01-01',
      },
    ],
    documents: [
      { id: 'pm_d1', title: 'Land Ownership Record (7/12 or RoR)', required_for_fields: ['land_ownership_ha'], issuing_authority: 'Patwari / Land Records Dept' },
      { id: 'pm_d2', title: 'Aadhaar Linked Bank Account', required_for_fields: ['bank_account'], issuing_authority: 'Scheduled Commercial Bank' },
    ],
    benefits: [
      { id: 'pm_b1', title: 'Annual Financial Support', amount: '₹6,000', frequency: 'Yearly (3 installments of ₹2,000)', description: 'Direct Benefit Transfer (DBT) into farmer bank account.' },
    ],
    exclusions: [
      { id: 'pm_ex1', title: 'Institutional Landholders', condition_field: 'institutional_landholder', condition_value: 'true', original_clause: 'All institutional land holders are excluded from scheme benefits.', overrides_all: true },
      { id: 'pm_ex2', title: 'Constitutional Post Holders', condition_field: 'constitutional_post_holder', condition_value: 'true', original_clause: 'Former and present holders of constitutional posts.', overrides_all: true },
      { id: 'pm_ex3', title: 'Income Tax Payers', condition_field: 'income_tax_payer_status', condition_value: 'true', original_clause: 'Persons who paid income tax in last assessment year.', overrides_all: true },
    ],
  },
  {
    id: 'magalir-urimai-thittam',
    title: 'Kalaignar Magalir Urimai Thittam (KMUT)',
    category: 'Women & Child',
    state: 'Tamil Nadu',
    language: 'Tamil',
    version: 'v1.2',
    last_amended: '2026-01-20',
    summary: 'Monthly rights grant of ₹1,000 to eligible female heads of households in Tamil Nadu.',
    conditions: [
      {
        id: 'ta1',
        field: 'income_threshold',
        field_display: 'Annual Family Income',
        operator: 'lte',
        value: 250000,
        unit: 'INR',
        original_clause: 'குடும்பத்தின் ஆண்டு வருமானம் ரூ. 2.50 லட்சத்திற்கு மிகாமல் இருக்க வேண்டும்.',
        mutability: 'MUTABLE',
        confidence: 0.94,
        language: 'ta',
        is_current: true,
        valid_from: '2024-01-01',
      },
      {
        id: 'ta2',
        field: 'age_min',
        field_display: 'Minimum Age',
        operator: 'gte',
        value: 21,
        unit: 'years',
        original_clause: 'குறைந்தபட்ச வயது 21 ஆண்டுகள் பூர்த்தியடைந்திருக்க வேண்டும்.',
        mutability: 'IMMUTABLE',
        confidence: 0.96,
        language: 'ta',
        is_current: true,
        valid_from: '2024-01-01',
      },
    ],
    documents: [
      { id: 'ta_d1', title: 'Smart Family Ration Card', required_for_fields: ['head_of_family'], issuing_authority: 'Civil Supplies Dept' },
    ],
    benefits: [
      { id: 'ta_b1', title: 'Monthly Assistance', amount: '₹1,000', frequency: 'Monthly', description: 'Direct grant to women head of household.' },
    ],
    exclusions: [
      { id: 'ta_ex1', title: 'Income Tax Payers', condition_field: 'income_tax_payer_status', condition_value: 'true', original_clause: 'கடந்த மதிப்பீட்டு ஆண்டில் வருமான வரி செலுத்தியவர்கள் தகுதியற்றவர்.', overrides_all: true },
    ],
  },
];

export const MOCK_EVALUATION_SCENARIOS: Record<string, EvaluationOutcome> = {
  eligible: {
    scheme_id: 'post-matric-sc-scholarship',
    scheme_title: 'Post-Matric Scholarship for Scheduled Caste Students',
    verdict: 'ELIGIBLE',
    overall_confidence: 1.0,
    readiness_score: 100,
    clause_details: [
      {
        clause_id: 'c1',
        field: 'caste_category',
        field_display: 'Caste Category',
        status: 'PASSED',
        mutability: 'IMMUTABLE',
        expected_value: 'SC',
        citizen_value: 'SC',
        proximity_score: 1.0,
        original_clause: 'Applicant must belong to Scheduled Caste (SC) category.',
      },
      {
        clause_id: 'c2',
        field: 'education_level',
        field_display: 'Minimum Qualification',
        status: 'PASSED',
        mutability: 'MUTABLE',
        expected_value: '>= 10th grade',
        citizen_value: '10th Pass',
        proximity_score: 1.0,
        original_clause: 'Must have passed 10th grade matriculation exam.',
      },
      {
        clause_id: 'c3',
        field: 'income_threshold',
        field_display: 'Family Annual Income Limit',
        status: 'PASSED',
        mutability: 'MUTABLE',
        expected_value: '<= ₹2,50,000',
        citizen_value: '₹2,10,000',
        proximity_score: 1.0,
        original_clause: 'Total annual family income must not exceed Rs. 2,50,000.',
      },
    ],
    missing_evidence: [],
    actionable_recommendations: [],
    citizen_summary: 'Congratulations! You meet all eligibility conditions for the Post-Matric SC Scholarship and have all required proofs ready.',
    evaluated_as_of: '2026-10-09',
  },

  needs_info: {
    scheme_id: 'post-matric-sc-scholarship',
    scheme_title: 'Post-Matric Scholarship for Scheduled Caste Students',
    verdict: 'NEEDS_MORE_INFO',
    overall_confidence: 0.67,
    readiness_score: 83.3,
    clause_details: [
      {
        clause_id: 'c1',
        field: 'caste_category',
        field_display: 'Caste Category',
        status: 'PASSED',
        mutability: 'IMMUTABLE',
        expected_value: 'SC',
        citizen_value: 'SC',
        proximity_score: 1.0,
        original_clause: 'Applicant must belong to Scheduled Caste (SC) category.',
      },
      {
        clause_id: 'c2',
        field: 'education_level',
        field_display: 'Minimum Qualification',
        status: 'PASSED',
        mutability: 'MUTABLE',
        expected_value: '>= 10th grade',
        citizen_value: '10th Pass',
        proximity_score: 1.0,
        original_clause: 'Must have passed 10th grade matriculation exam.',
      },
      {
        clause_id: 'c3',
        field: 'income_threshold',
        field_display: 'Family Annual Income Limit',
        status: 'UNKNOWN',
        mutability: 'MUTABLE',
        expected_value: '<= ₹2,50,000',
        citizen_value: 'Not Provided (Unknown)',
        proximity_score: 0.5,
        original_clause: 'Total annual family income must not exceed Rs. 2,50,000.',
        failure_reason: 'Annual family income was indicated as unknown or missing.',
      },
    ],
    missing_evidence: [
      {
        missing_fact: 'Annual Family Income',
        required_document: 'Annual Income Certificate',
        issuing_authority: 'Revenue Department / Tehsildar Office',
        governing_clause: 'Total annual family income must not exceed Rs. 2,50,000.',
        citizen_action: 'Obtain an Income Certificate from your local Revenue Officer stating annual income <= ₹2.5L.',
      },
    ],
    actionable_recommendations: [
      {
        target_field: 'income_threshold',
        current_val: 'Missing Fact',
        required_val: '<= ₹2,50,000',
        recommendation: 'Provide your family annual income value to resolve the UNKNOWN status.',
        difficulty: 'Easy',
      },
    ],
    citizen_summary: 'Your eligibility cannot be fully confirmed because family income is missing. Submit an Income Certificate to reach 100% readiness.',
    evaluated_as_of: '2026-10-09',
  },

  ineligible: {
    scheme_id: 'post-matric-sc-scholarship',
    scheme_title: 'Post-Matric Scholarship for Scheduled Caste Students',
    verdict: 'INELIGIBLE',
    overall_confidence: 1.0,
    readiness_score: 90.7,
    clause_details: [
      {
        clause_id: 'c1',
        field: 'caste_category',
        field_display: 'Caste Category',
        status: 'PASSED',
        mutability: 'IMMUTABLE',
        expected_value: 'SC',
        citizen_value: 'SC',
        proximity_score: 1.0,
        original_clause: 'Applicant must belong to Scheduled Caste (SC) category.',
      },
      {
        clause_id: 'c2',
        field: 'education_level',
        field_display: 'Minimum Qualification',
        status: 'PASSED',
        mutability: 'MUTABLE',
        expected_value: '>= 10th grade',
        citizen_value: '10th Pass',
        proximity_score: 1.0,
        original_clause: 'Must have passed 10th grade matriculation exam.',
      },
      {
        clause_id: 'c3',
        field: 'income_threshold',
        field_display: 'Family Annual Income Limit',
        status: 'FAILED',
        mutability: 'MUTABLE',
        expected_value: '<= ₹2,50,000',
        citizen_value: '₹3,20,000',
        proximity_score: 0.72,
        original_clause: 'Total annual family income must not exceed Rs. 2,50,000.',
        failure_reason: 'Annual family income ₹3,20,000 exceeds ceiling of ₹2,50,000 by ₹70,000.',
      },
    ],
    missing_evidence: [],
    actionable_recommendations: [
      {
        target_field: 'income_threshold',
        current_val: '₹3,20,000',
        required_val: '<= ₹2,50,000',
        recommendation: 'Reduce annual family income by Rs. 70,000 to Rs. 250,000 or below (or re-verify taxable vs gross income allowances).',
        difficulty: 'Medium',
      },
    ],
    citizen_summary: 'You are currently ineligible because family annual income (₹3,20,000) exceeds the ₹2,50,000 ceiling.',
    evaluated_as_of: '2026-10-09',
  },
};

export const MOCK_BENCHMARK_METRICS: BenchmarkMetrics = {
  evaluation_mode: '[LIVE NEO4J AURADB VERIFIED & MOCKED GROQ EVALUATION]',
  hand_derived_verdict_accuracy: 1.0,
  confusion_matrix: {
    eligible: { eligible: 3, ineligible: 0, needs_more_info: 0 },
    ineligible: { eligible: 0, ineligible: 7, needs_more_info: 0 },
    needs_more_info: { eligible: 0, ineligible: 0, needs_more_info: 2 },
  },
  multilingual_extraction: {
    precision: 0.5988,
    recall: 0.775,
    per_language: {
      en: { precision: 0.4286, recall: 0.75 },
      hi: { precision: 0.8, recall: 0.8 },
      ta: { precision: 0.6667, recall: 0.8 },
      te: { precision: 0.5, recall: 0.75 },
    },
  },
  timing_benchmark: {
    in_memory: { full_ms: 0.564, incremental_ms: 0.493, speedup: 1.14 },
    live_neo4j: { full_ms: 1285.244, incremental_ms: 499.795, speedup: 2.57, status: 'Connected & Verified on Live Neo4j Database' },
  },
};
